name: flutter_modules
description: Template of some commonly used widgets.
version: 0.1.1
homepage: https://github.com/Covisoft/flutter_modules

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.8+1
  photo_manager: ^2.1.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  